### ISSUE TITLE
Biomaps are not properly saved

### ISSUE THREAD

**Issue by AdelGuiot** [pchaillo/prism_imaging#2]
25/04/23
MatLab R2019a
Windows 10
new_laser branch

Biomaps are properly displayed on the interface, but the software throws an error that causes it not to save the biomap

The error in question is caused by line 916: record_BIOmap2(carte_x,carte_y,carte_z,bio_map,nom, limits)

----

Error: File: record_BIOmap2.m Line: 1 Column: 1 Invalid use of operator.

**Comment by pchaillo** [comment]
Hi Adel, 

It was due to an non fixed conflict in the code, it's fix in the branch fix_mzXML_bug that will be merge in the main branch soon.

Thanks,

Best,

Paul
