### ISSUE TITLE
Chromatograms fail to get plotted 

### ISSUE THREAD

**Issue by AdelGuiot** [pchaillo/prism_imaging#3]
25/04/2023
MatLab R2022b
3D_Export Branch
Windows 10 

Some biomaps seemingly load properly on this build. However, the chromatograms do not get plotted. Instead, MatLab returns a blank window and an error.

----

The error pertains to line 1432 of the interface: plot_chromatogram(mzXML.Struct)

Console log:

Unable to perform assignment because the indices on the left side are not compatible with the
size of the right side.

Error in plot_chromatogram (line 11)
    t_i(i) = file2(i).retentionTime;

Error in mapping_APP_7/PlotChromatogramButtonPushed (line 1432)
            plot_chromatogram(mzXML.Struct)

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by pchaillo** [comment]
Hi Adel, 

This problem was due to Matlab update between R2019a and R2022b.

I update the problem and it's now working with the last version of matlab.

Bests,

Paul
