### ISSUE TITLE
Edited map files are not saved

### ISSUE THREAD

**Issue by AdelGuiot** [pchaillo/prism_imaging#7]
04/05/2023
Windows 11
MatLab R2022b
3D_Export Branch (The affected code is identical to Main)

Edited map files in the Map Rectification tab are not automatically saved. The code seems to execute properly as there is no error message. 

I have pasted the script responsible for Map file rectification below:

function LaunchRectificationButtonPushed(app, event)
            path(path,'map files')
            path(path,'code/code_for_reconstruction')
            path(path,'code/code_for_analysing')
            path(path,'code/code_for_recording')

            
            nom_map_r = app.NameofthemapEditField.Value;
            nom_map = strcat(nom_map_r,'.map');
            %out = load(nom_map); % load topographical map. Remove any dot in the file name
            carte = load_map4_fcn(nom_map);
            
            nom_new_map_r = app.NameofthecorrectedmapEditField.Value;
            nom_map_new = strcat(nom_new_map_r,'.map');
            
            seuil_min = app.MinimumthresholdmmEditField.Value;
            seuil_max = app.MaximumthresholdmmEditField.Value;
            
            carte_z = carte.z;
            
            [carte_z2, nb_err ]= map_rectification(carte_z,seuil_min,seuil_max);

            carte_f = click_loop_multi(carte,carte_z2,seuil_min,seuil_max);
            
            seuil = 0;
            
            if isfield(carte,'time')
                time_diff_med = record_map4(carte.x,carte.y,carte_f,nom_map_new,seuil,carte.time);
            else
                record_map2(carte.x,carte.y,carte_f,nom_map_new,seuil);
            end

**Comment by AdelGuiot** [comment]
I figured out what the issue was. In order for the edited map to be saved, the user must press "S" on the displayed figure. While the internal logic makes sense, I suggest making this clearer to the user, via a prompt or something that would accomplish the same thing.

**Comment by pchaillo** [comment]
Hi Adel,

For sure you're right, adding at least a message to let know to the user what he should do to save (but also to help him with the previous step) . Also we need to add more documentation on Git in order to increase the accessibility.

Thanks a lot for your feedback it's very usefull.

Bests,

Paul
